### ISSUE TITLE
ProfileJsonResponse 结合laravel 5.4 & dingo api 不工作

### ISSUE THREAD

**Issue by Xiongzhenyu** [ElfSundae/holly#8]
你好 , 我是在laravel-debugbar issues 过来的
有个问题： 我创建了ProfileJsonResponse中间件，$middlewareGroups 也有引用，可是api界面依旧不工作，请问还需要修改哪里嘛？

**Comment by ElfSundae** [comment]
「api 界面不工作」是什么意思？
ProfileJsonResponse 只是给最终输出的 json 数据里添加了 debugbar 的数据，跟界面无关，也不会影响 debugbar 的界面。

如果你是说在浏览器里访问 api 接口时不显示底部的 debugbar 的话，那就跟这个 middleware 没关系了。

debugbar 是一段 html 代码，要嵌入到网页中才能看到，而返回纯 json 数据的 api 接口没有 html 网页，所以 debugbar 就没法显示了，具体原理参阅 debugbar 的文档。如果你非要在浏览器里显示  api 请求的
 debugbar 的话，可以新建个 middleware ，把所有 `JsonResponse` 给转换成 string， 然后设置 response header 里的 `Content-Type` 为 `text/html` 就可以了。

**Comment by ElfSundae** [comment]
我对 Dingo 不了解，你是不是说的[这个问题](https://github.com/barryvdh/laravel-debugbar/issues/252#issuecomment-286680153)
